language: node_js
node_js:
  - '5'

branches:
  only:
    - master
    - release

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GITHUB_REPO: 'dojocon-japan/dojocon-japan.github.io'

before_install:
  - rvm install 2.1

install:
  - npm install
  - gem install jekyll html-proofer

script:
  - jekyll build
  - npm test
  - htmlproofer ./_site --check-html --url-ignore "/linkedin\.com/"

# after_success:
#   - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "master" ]; then exit 0; fi
#   - git push -f -q "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" master:gh-pages > /dev/null 2>&1

sudo: false
