exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - npm-debug.log
  - README.md
  - LICENSE

title: DojoCon Japan 2016
description: DojoCon Japan 2016
url: http://dojocon.coderdojo.jp
baseurl: /

environment: development
