# Site settings
title: DojoCon Japan 2016 - The more dojos, the more cool coders. -
description: DojoCon Japan 2016 - The more dojos, the more cool coders. -
url: http://dojocon.coderdojo.jp
baseurl: ''
entryurl: ''

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - npm-debug.log
  - README.md
  - LICENSE
